/*
 * Circle.java  	1.2 30/01/2019
 * 
 * This is a template for problem sheet 1
 * 
 * Copyright (c) University of Sheffield 2019
 */

/** 
* Circle.java
* 
* 
* @version 1.1 30/01/2019
* 
* @author Maria-Cruz Villa-Uriol/Richard Clayton
*/

package uk.ac.sheffield.com1003.problemsheet1;

public class CircleTemplate {
	// constructor
	public Circle( double r, int x, int y ){
		radius = r;
		xPosition = x;
		yPosition = y;
	}
	
	// methods -- you should remove the comments, and complete the method bodies
	/*
	public double getRadius(){
		// add your own code here to return the radius of the circle
	}
	public void getPosition( int currentX, int currentY ){
		// add your own code here to get the centre of the circle
	}
	public void setRadius( double newRadius ){
		// add your own code here to set the radius of the circle
	}
	public void setPosition( int newX, int newY ){
		// add your own code here to set the centre of the circle
	}	
	*/	
	
	
	// instance variables
	private double radius;
	private int xPosition;
	private int yPosition;
}