/*
 * Line.java  	1.1 30/01/2018
 * 
 * This is a template for problem sheet 1
 *
 * Copyright (c) University of Sheffield 2019
 */

/** 
* Line.java
*  
* @version 1.1 30/01/2019
* 
* @author Maria-Cruz Villa-Uriol
*/
package uk.ac.sheffield.com1003.problemsheet1;

public class LineTemplate {

	// constructor
	public Line( int x1, int y1, int x2, int y2 ){
		xStart = x1;
		yStart = y1;
		xEnd = x2;
		yEnd = y2;
	}
	
	// methods -- you should remove the comments, and complete the method bodies
	/*
	public double setStartPoint( int x1, int y1 ){
		// add your own code here to set for this line the coordinates of the start point 
	}
	public double setEndPoint( int x1, int y1 ){
		// add your own code here to set for this line the coordinates of the end point 
	}
	public void getStartPoint ( int currentX, int currentY ){
		// add your own code here to get for this line the coordinates of the start point 
	}
	public void getEndPoint ( int newX, int newY ){
		// add your own code here to get for this line the coordinates of the end point 
	}	
	public void getLength( double newLength ){
		// add your own code here to compute and return length of line
	}
	*/	
	
	
	// instance variables
	private int xStart;
	private int yStart;
	private int xEnd;
	private int yEnd;
}